Created archive.py
The-Coding-Academy/coding-bot-v4 pull request #22
Opened 2021-07-08 05:15 UTC by SohamGhugare

Since Swas loves to archive channels very too often, here's an archive command which will archive the channel. 
(Can be used only by admins, and has a seperate command for setting the archive category)

2021-08-05 16:39 UTC, BobDotCom requested changes
Would be better to set a static archive category by default. You can get the id of the current category and place it in the init instead of initializing to None.

2021-08-05 16:49 UTC, SohamGhugare commented
Alright i will do that soon

2021-08-06 04:43 UTC, SohamGhugare commented
Alright done, havent tested it but should work

2021-08-25 15:08 UTC, BobDotCom approved these changes

2021-08-25 15:09 UTC, merged